# Generated by Django 5.1.2 on 2025-11-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(help_text='Original file path relative to static directory', max_length=500)),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('cloudinary_url', models.URLField(help_text='Full Cloudinary URL', max_length=1000)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID', max_length=500, null=True)),
                ('format', models.CharField(blank=True, help_text='Image format (webp, jpg, png, etc.)', max_length=10, null=True)),
                ('width', models.IntegerField(blank=True, help_text='Image width in pixels', null=True)),
                ('height', models.IntegerField(blank=True, help_text='Image height in pixels', null=True)),
                ('file_size', models.BigIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('was_converted', models.BooleanField(default=False, help_text='Whether the image was converted to WebP')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='When the image was uploaded')),
            ],
            options={
                'db_table': 'media_assets',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['original_path'], name='media_asset_origina_98b58c_idx'), models.Index(fields=['cloudinary_public_id'], name='media_asset_cloudin_bfad95_idx')],
            },
        ),
    ]
